---
#Deployer Settings
virtualenv: /opt/dtaas/
ansible_python_interpreter: "{{ virtualenv is none | ternary('python3', virtualenv ~ '/bin/python' ) }}"


dl_cloud_image: 'CentOS-8-GenericCloud-8.4.2015'

#DataLake Infrastructure Settings
dl_private_network: dlaas2_private
dl_subnet_name: 'dtaas2_subnet'
dl_subnet_cidr: 10.0.65.0/24
dl_subnet_gateway: 10.0.65.1
dl_router_name: 'r2_prv_to_external'



