---
- include_vars: api.yml

- name: Create file with API environment variables
  template:
     src: api_env.j2
     dest: "{{ dtaas_api_config }}"
     mode: "0666"

- name: Create API service file
  become: true
  template:
   src: api_service.j2
   dest: /etc/systemd/system/dtaas-api.service
   mode: "0666"
  notify: restart-dtaas-api

- name: Start API service
  become: true
  systemd:
    name: dtaas-api.service
    enabled: true
    state: started
  