---
- include_vars: api.yml

- name: Create file with API environment variables
  template:
     src: api_env.j2
     dest: "{{ dtaas_api_config }}"
     mode: "0666"

- name: Create folder for api service
  file:
    path: ~/.config/systemd/user
    state: directory
    mode: "0755"

- name: Create API service file
  template:
   src: api_service.j2
   dest:  "{{ansible_env.HOME }}/.config/systemd/user/dtaas-api.service"
   mode: "0666"
  notify: restart-dtaas-api

- name: Enable linger for dtaas-user
  become: true
  command: loginctl enable-linger "{{ansible_user}}"

- name: Enable systemd unit with user scope 
  command: systemctl --user enable dtaas-api 
  
- name: Start API service
  systemd:
    scope: user
    name: dtaas-api.service
    enabled: true
    state: started
  