---
- name: Create network, security group, and launch a server
  hosts: virtualmachines
  gather_facts: no
  vars_files:
    - parameters.yml
    - clouds.yaml

  tasks:
    

           
    - name: Create a new VM
      openstack.cloud.server:
        state: present
        name: "{{ vm_name }}"
        image: "{{ vm_image }}"
        flavor_ram: "{{ vm_flavor_ram }}"
        boot_from_volume: True
        volume_size: "{{ vm_volume_size }}"
        security_groups: "{{ security_group.security_group.name }}"
        network: "{{ network.network.name }}"
        key_name: "{{ key_name }}"
        auto_ip: "{{ auto_ip | default('yes') }}"
      register: server


    - name: Get floating IP details
      openstack.cloud.floating_ip:
        server: "{{ server.server.name }}"
        reuse: yes
      register: floating_ip_details

    - name: Add new VM to inventory
      add_host:
        name: "{{ server.server.name }}"
        ansible_host: "{{ floating_ip_details.floating_ip.floating_ip_address }}"
        ansible_user: centos
        ansible_ssh_private_key_file: "{{private_key_path}}"
        ansible_python_interpreter: /usr/bin/python3
        groups: dynamically_created_hosts

- name: Generate static inventory file from current in-memory inventory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create static inventory file from template
      template:
        src: template.j2
        dest: /home/centos/ansible_material/inventory/03_inventory.yml

