---
# tasks file for openstack-infra
# This task return without changes if network exists, and fails if there is more then one networks with the name {{ dl_private_network }}

- include_tasks: prechecks.yml
- include_tasks: networking.yml
- include_tasks: sshkeys.yml
- include_tasks: compute.yml