---
- name: "Add new VM to inventory"
  add_host:
    name: "{{ r_create_instance.server.name }}"
    ansible_host: "{{ r_get_floating_ip_info.floating_ip.floating_ip_address }}"
    ansible_user: "{{ dl_instance_user }}"
    #TODO maybe avoid this
    ansible_ssh_private_key_file: "{{ dl_instance_sshpvt_path }}"
    groups: dynamically_created_hosts
  tags:
   - infra 
   - vm 
   - inventory

- name: Create static inventory file from template
  template:
    src: template.j2
    dest: "{{ inventory_dir ~ '/datalake-infra' }}"
  tags:
    - infra 
    - vm 
    - inventory
