---
#Centos8 Specific Settings
#List of Dicts with yum repository infos
yum_repositories:
  - repository:
      id: 'appstream'
      name: 'CentOS Linux 8 vault - AppStream'
      baseurl: 'http://vault.centos.org/centos/8/AppStream/x86_64/os/'
      filename: '/etc/yum.repos.d/CentOS-Linux-AppStream'
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial'
  - repository:
      id: 'baseos'
      name: 'CentOS Linux 8 vault - BaseOS'
      baseurl: 'http://vault.centos.org/centos/8/BaseOS/x86_64/os/'
      filename: '/etc/yum.repos.d/CentOS-Linux-BaseOS'
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial'
  - repository:
      id: 'extras'
      name: 'CentOS Linux 8 vault - Extras'
      baseurl: 'http://vault.centos.org/centos/8/extras/x86_64/os/'
      filename: '/etc/yum.repos.d/CentOS-Linux-Extras'
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial'
  - repository:
      id: 'mongodb'
      name: ''
      baseurl: 'https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/'
      filename: '/etc/yum.repos.d/CentOS-Linux-MongoDB'
      gpgkey: 'https://www.mongodb.org/static/pgp/server-4.4.asc'


#List of system packages to install
system_packages:
  - python39
  - git
  - epel-release
  - mongodb-org
  - nginx

system_packages_epel:
  - certbot 
  - python3-certbot-nginx
  



