#!/usr/bin/env bash

export OS_AUTH_TYPE=v3applicationcredential
export OS_AUTH_URL=https://adacloud.hpc.cineca.it:5000
export OS_IDENTITY_API_VERSION=3
export OS_REGION_NAME="RegionOne"
export OS_INTERFACE=public
export OS_APPLICATION_CREDENTIAL_ID=e2b6f62ccaf94833a0f4c43c21d3d4d2
export OS_APPLICATION_CREDENTIAL_SECRET=g1Yk1ULbOuOCnafv02lHv5FqLElKXTI8TKXFottMDMFof7OXs5UDRT2tRbdBCnKuHl38PXvSNKHhvM7H-SM2wQ

