---
- name: test role
  hosts: cloud-infra 
  tasks:
    - include_role: 
        name: dlaas
        tasks_from: init

    - include_role: 
        name: dlaas
      vars:
        ansible_python_interpreter: "{{ hostvars[inventory_hostname]['ansible_python_interpreter'] }}"
