# Network parameters
network_name: "dl_net"
subnet_name: "dl_subnet"
router_name: "dl_router"
external_network: "externalNetwork"
subnet_cidr: "192.168.0.0/24"
gateway_ip: "192.168.0.254"
admin_state_up: "yes"
security_group_name: "dl_firewall" 

# VM parameters
# The vm_image must be known in advance and provided in the tenant to be used.
vm_name: "dl_vm"
vm_image: "CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64"
vm_flavor_ram: 30000
vm_volume_size: 100
key_name: "dl_vm_key"
private_key_path: "/home/lbabetto/.ssh/dl_vm_private.pem"
public_key_path: "/home/lbabetto/.ssh/dl_vm_public.pub"
auto_ip: yes
static_ip: 130.186.19.0/24
cloud: "openstack"

# HPC parameters
login_nodes: 130.186.24.4/30
compute_nodes: 130.186.24.0/28
s3_bucket: s3poc
s3_endpoint_url: https://s3ds.g100st.cineca.it/
pfs_path_prefix: /g100_s3/DRES_s3poc
s3_access_key: AKIAY6149M5O7OSVIMF8
s3_secret_key: j01JKfTU2sjjT40htXVM0qEke5f/JRKIGz7qby/G
s3_region: cinecahpc

# DTAAS-TUI server config
config_server_user: lbabetto  # username on HPC
config_server_host: login02-ext.g100.cineca.it  # hostname of login node
config_server_venv_path: ~/virtualenvs/dtaas  # path of virtual environment with necessary libraries
config_server_ssh_key: ~/.ssh/luca-g100  # path to SSH key on VM for accessing HPC
config_server_compute_partition: g100_usr_prod  # partition used for HPC jobs
config_server_upload_partition: g100_all_serial  # partition used for uploading to S3
config_server_account: EUCC_staff_2  # account for HPC jobs
config_server_qos: normal  # QoS for HPC jobs
config_server_mail: l.babetto@cineca.it  # email address for info on HPC job status

# Constants for JWT token generation and verification
jwt_issuer: "cineca_or_ifab"
jwt_secret: "test-s3"  # Make sure to use a secure, unique secret in production
jwt_lifetime_seconds: 600
jwt_algorithm: "HS256"
