---
- name: Setup Python
  hosts: my_vm
  become: yes
  gather_facts: yes

  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Ensure python3 is installed
      ansible.builtin.package:
        name: python3
        state: present
        use_backend: auto

