---
- name: Create Openstack DLaaS Instance 
  openstack.cloud.server:
    state: present
    name: "{{ dl_instance_name }}"
    image: "{{ dl_cloud_image }}"
    flavor_ram: "{{ dl_instance_ram }}"
    boot_from_volume: True
    volume_size: "{{ dl_instance_volume_size }}"
    security_groups: "{{ dl_security_group_name }}"
    network: "{{ dl_private_network }}"
    key_name: "{{ dl_os_sshkey_name}}"
    auto_ip: 'no'
    cloud: "{{dl_cloud}}"
    userdata: "{{dl_instance_user_data}}"
  register: r_create_instance
  tags:
    - infra
    - vm 

- name: Get a Floating IP address and Assign it to DLaaS Instance
  openstack.cloud.floating_ip:
    server: "{{ r_create_instance.server.name }}"
    cloud: "{{dl_cloud}}"
    network: "{{ openstack_external_network }}"
    wait: true
    reuse: false
  register: r_get_floating_ip_info
  tags:
    - infra
    - vm
- debug:
    msg: "{{r_get_floating_ip_info}}"
- name: Wait SSH on Server is Ready
  wait_for:
    port: 22 
    host: "{{ r_get_floating_ip_info.floating_ip.floating_ip_address }}" 
  tags: ['infra','vm']


