# Create a file called openstack.yaml, add the following content and run
# $> ansible-inventory --list -vvv -i openstack.yaml

plugin: openstack.cloud.openstack

all_projects: false
expand_hostvars: true

fail_on_errors: true

only_clouds:

  - "openstack"

strict: true
