---
# handlers file for dtaas
- name: yum-clean-metadata
  become: true
  command: 'yum clean metadata'

- name: restart-mongo
  become: true
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
- name: restart-dtaas-api
  ansible.builtin.systemd_service:
    scope: user
    name: dtaas-api
    daemon_reload: true
    state: restarted

 