---
dl_instance_ansible_python_interpreter: '/usr/bin/python3'
## defaults file for openstack-infra
dl_cloud: 'openstack'

##Compute 
#Keys
#local paths for generating or importing sshkey to Openstack User Account
dl_instance_sshpub_path: "{{ lookup('env', 'HOME') ~ '/dtaas_sshkey.pub'}}"
dl_instance_sshpvt_path: "{{ dl_instance_sshpub_path | regex_replace('\\..*', '') ~ '.key' }}"
#Instance
dl_os_sshkey_name: "{{ dl_instance_sshpub_path | basename | regex_replace('\\..*', '')}}"
dl_instance_name: 'DataLake_as_a_Service'
dl_instance_ram: 30000 #MB
dl_instance_volume_size: 100 #GB
dl_instance_user: "datalake"

dl_instance_user_data: |
  #cloud-config
  system_info:
          default_user:
            name: "{{ dl_instance_user }}"

#Cloud image:
dl_cloud_image: 'CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64'

##Networking 
dl_private_network: dlaas_private
dl_subnet_name: 'dtaas_subnet'
dl_subnet_cidr: 10.0.63.0/24
dl_subnet_gateway: 10.0.63.1

login_nodes: 130.186.24.4/30
compute_nodes: 130.186.24.0/28

setup_ip: 130.186.19.0/24
user_ips: 130.186.19.0/24

dl_router_name: 'r1_prv_to_external'
dl_security_group_name: 'dlaas_security_group'
dl_security_group_rules:
  - { protocol: 'tcp', port_range_min: 22, port_range_max: 22, remote_ip_prefix: '{{ setup_ip }}' }
  - { protocol: 'tcp', port_range_min: 27017, port_range_max: 27017, remote_ip_prefix: '{{ login_nodes }}'}
  - { protocol: 'tcp', port_range_min: 27017, port_range_max: 27017, remote_ip_prefix: '{{ compute_nodes }}'}
  - { protocol: 'tcp', port_range_min: 8080, port_range_max: 8080, remote_ip_prefix: '{{ user_ips }}'}
