---
#this is a very specific task to setup a python environment in G100 cineca account
- include_vars: "{{item}}"
  loop:
    - hpc_packages.yml
    - dtaas-tui.yml
  tags: ['hpc'] 

- name: Set python ansible_python_interpreter
  set_fact:
    ansible_python_interpreter: "/cineca/prod/opt/compilers/python/3.11.7/gcc--10.2.0/bin/python3"
  tags: ['hpc'] 

- name: Load python environment module from .bashrc
  #shell: "module load python; grep 'module load python' .bashrc &>/dev/null || echo 'module load python' >> .bashrc" 
  raw: grep 'module load python' .bashrc || sed -i  '$ a \module load python' .bashrc
  tags: ['hpc'] 

- name: Install python dependences
  pip:
    name: "{{ hpc_python_packages }}"
    virtualenv: "{{ config_server_venv_path }}"
    virtualenv_command: "python3 -m venv {{config_server_venv_path}}"
  tags: ['hpc']

- name: Add HPC Login Node's host keys to DataLake Server account
  delegate_to: DataLake_as_a_Service
  ansible.builtin.known_hosts:
    name: "{{ hpc_login_node }}"
    key: "{{ item }}"
    state: present
  loop: "{{ hpc_login_node_ssh_host_keys }}"
  tags: ['infra','vm']